include $(THEOS)/makefiles/common.mk

TWEAK_NAME = FullscreenViewDisableNativeSplitViewIPadOnlyForIOS11
FullscreenViewDisableNativeSplitViewIPadOnlyForIOS11_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
