(function(g){var window=this;var JAa=function(a,b){return g.Vb(a,b)},f6=function(a){g.Jm(a,"zx",g.xb());
return a},g6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Mm(a.g,b,c)},KAa=function(a,b){var c=[];
g.tk(b,function(a){try{var b=g.ZC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.YC(b)&&c.push(a):c.push(a)},a);
return c},LAa=function(a,b){var c=KAa(a,b);
(0,g.B)(c,function(a){g.ZC.prototype.remove.call(this,a)},a)},MAa=function(a,b,c,d){var e=new g.Am(null,void 0);
a&&g.Bm(e,a);b&&g.Cm(e,b);c&&g.Dm(e,c);d&&g.Em(e,d);return e},NAa=function(a){g.TF[a]&&(a=g.TF[a],(0,g.B)(a,function(a){g.RF[a]&&delete g.RF[a]}),a.length=0)},OAa=function(a){var b=g.QF();
if(b)if(b.clear(a),a)NAa(a);else for(var c in g.TF)NAa(c)},h6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.um;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",PAa(this,a.capabilities||""),QAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},PAa=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Fa(JAa,RAa)).forEach(function(b){a.capabilities.add(b)})},QAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},i6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},j6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},SAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},TAa=function(a){return new i6(a)},UAa=function(a){return g.za(a)?(0,g.H)(a,TAa):[]},k6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},l6=function(a){return g.za(a)?"["+(0,g.H)(a,k6).join(",")+"]":"null"},m6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},VAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},n6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},o6=function(a,b){return g.Ma(a,function(a){return j6(a,b)})},WAa=function(){var a=(0,g.MG)();
a&&LAa(a,a.g.Rd(!0))},p6=function(){var a=g.PG("yt-remote-connected-devices")||[];
g.ib(a);return a},XAa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},YAa=function(a){g.OG("yt-remote-connected-devices",a,86400)},r6=function(){if(q6)return q6;
var a=g.PG("yt-remote-device-id");a||(a=m6(),g.OG("yt-remote-device-id",a,31536E3));for(var b=p6(),c=1,d=a;g.C(b,d);)c++,d=a+"#"+c;return q6=d},s6=function(){var a=p6(),b=r6();
g.C(a,b);g.RG()&&g.kb(a,b);a=XAa(a);if(g.Qa(a))try{g.zG("remote_sid")}catch(c){}else try{g.yG("remote_sid",a.join(","),-1)}catch(c){}},ZAa=function(){return g.PG("yt-remote-session-browser-channel")},$Aa=function(){return g.PG("yt-remote-local-screens")||[]},aBa=function(){g.OG("yt-remote-lounge-token-expiration",!0,86400)},bBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)($Aa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.jm)(c,function(a){return!g.C(b,a)})&&aBa();
g.OG("yt-remote-local-screens",a,31536E3)},cBa=function(a,b){g.OG("yt-remote-session-browser-channel",a);
g.OG("yt-remote-session-screen-id",b);var c=p6(),d=r6();g.C(c,d)||c.push(d);YAa(c);s6()},t6=function(a){a||(g.QG("yt-remote-session-screen-id"),g.QG("yt-remote-session-video-id"));
s6();a=p6();g.Ua(a,r6());YAa(a)},dBa=function(){if(!u6){var a=g.jD();
a&&(u6=new g.TC(a))}return u6?!!u6.get("yt-remote-use-staging-server"):!1},eBa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},fBa=function(a,b){var c=g.Cd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Zc(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},gBa=function(){var a=eBa(),b=window.document.getElementById(a),c=b&&g.dF(b,"loaded");
c||b&&!c||(b=fBa(a,function(){g.dF(b,"loaded")||(g.cF(b,"loaded","true"),g.XF(a),g.SD(g.Fa(OAa,a),0))}))},v6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},hBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},w6=function(a){a.length?iBa(a.shift(),function(){w6(a)}):x6()},jBa=function(a){return"chrome-extension://"+a+y6},iBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},z6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},x6=function(){var a=hBa();
a&&a(!1,"No cast extension found")},A6=function(){if(kBa){var a=2,b=hBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;iBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",x6,c)}},lBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(A6(),a({command:"cast.sender.init"}))},mBa=function(){A6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);w6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+y6,"//www.gstatic.com/eureka/clank"+y6])},B6=function(a,b,c){g.L.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.dd=b;this.B=(0,g.z)(this.OI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},C6=function(){},D6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Qm(this);this.l=new g.sg;this.l.setInterval(250)},oBa=function(a,b,c){a.Bj=1;
a.lh=f6(b.clone());a.Mi=c;a.C=!0;nBa(a,null)},E6=function(a,b,c,d,e){a.Bj=1;
a.lh=f6(b.clone());a.Mi=null;a.C=c;e&&(a.eD=!1);nBa(a,d)},nBa=function(a,b){a.gk=(0,g.G)();
F6(a);a.Eh=a.lh.clone();g6(a.Eh,"t",a.D);a.lm=0;a.Rc=a.g.Pq(a.g.fm()?b:null);0<a.wr&&(a.fp=new g.Uk((0,g.z)(a.uE,a,a.Rc),a.wr));a.A.T(a.Rc,"readystatechange",a.aU);var c=a.mi?g.bc(a.mi):{};a.Mi?(a.Op="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Eh,a.Op,a.Mi,c)):(a.Op="GET",a.eD&&!g.yd&&(c.Connection="close"),a.Rc.send(a.Eh,a.Op,null,c));a.g.sf(1)},rBa=function(a,b,c){for(var d=!0;!a.Wh&&a.lm<c.length;){var e=pBa(a,c);
if(e==G6){4==b&&(a.mh=4,H6(15),d=!1);break}else if(e==qBa){a.mh=4;H6(16);d=!1;break}else I6(a,e)}4==b&&0==c.length&&(a.mh=1,H6(17),d=!1);a.yf=a.yf&&d;d||(J6(a),K6(a))},pBa=function(a,b){var c=a.lm,d=b.indexOf("\n",c);
if(-1==d)return G6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return qBa;d+=1;if(d+c>b.length)return G6;var e=b.substr(d,c);a.lm=d+c;return e},tBa=function(a,b){a.gk=(0,g.G)();
F6(a);var c=b?window.location.hostname:"";a.Eh=a.lh.clone();g.Jm(a.Eh,"DOMAIN",c);g.Jm(a.Eh,"t",a.D);try{a.zf=new window.ActiveXObject("htmlfile")}catch(n){J6(a);a.mh=7;H6(22);K6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in L6)k=L6[l];else if(l in sBa)k=L6[l]=sBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=L6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.$c(g.vc("b/12014412"),d);a.zf.open();a.zf.write(g.Rc(c));a.zf.close();a.zf.parentWindow.m=(0,g.z)(a.dT,a);a.zf.parentWindow.d=(0,g.z)(a.rC,a,!0);a.zf.parentWindow.rpcClose=(0,g.z)(a.rC,a,!1);c=a.zf.createElement("DIV");a.zf.parentWindow.document.body.appendChild(c);d=g.Ic(a.Eh.toString());d=g.rb(g.Fc(d));d=g.$c(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);
a.g.sf(1)},F6=function(a){a.lv=(0,g.G)()+a.B;
uBa(a,a.B)},uBa=function(a,b){if(null!=a.Ak)throw Error("WatchDog timer not null");
a.Ak=M6((0,g.z)(a.uT,a),b)},N6=function(a){a.Ak&&(g.w.clearTimeout(a.Ak),a.Ak=null)},K6=function(a){a.g.zy()||a.Wh||a.g.Ro(a)},J6=function(a){N6(a);
g.af(a.fp);a.fp=null;a.l.stop();g.Wm(a.A);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.zf&&(a.zf=null)},I6=function(a,b){try{a.g.kC(a,b),a.g.sf(4)}catch(c){}},wBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;vBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){wBa(a,b,c,d,f)},f)})}},vBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{O6(d),c(!0)}catch(e){}};
d.onerror=function(){try{O6(d),c(!1)}catch(e){}};
d.onabort=function(){try{O6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{O6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},O6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},xBa=function(a){this.g=a;
this.l=new C6},yBa=function(a){var b=P6(a.g,a.Fk,"/mail/images/cleardot.gif");
f6(b);wBa(b.toString(),5E3,(0,g.z)(a.aI,a),3,2E3);a.sf(1)},R6=function(a){var b=a.g.H;
if(null!=b)H6(5),b?(H6(11),Q6(a.g,a,!1)):(H6(12),Q6(a.g,a,!0));else if(a.xe=new D6(a,void 0,void 0,void 0),a.xe.mi=a.tr,b=a.g,b=P6(b,b.fm()?a.il:null,a.vr),H6(5),!g.wd||g.rc(10))g6(b,"TYPE","xmlhttp"),E6(a.xe,b,!1,a.il,!1);else{g6(b,"TYPE","html");var c=a.xe;a=!!a.il;c.Bj=3;c.lh=f6(b.clone());tBa(c,a)}},S6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new C6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},zBa=function(a,b){this.g=a;
this.map=b;this.context=null},ABa=function(a){g.cf.call(this,"statevent",a)},BBa=function(a,b){g.cf.call(this,"timingevent",a);
this.size=b},CBa=function(a){g.cf.call(this,"serverreachability",a)},FBa=function(a){DBa(a);
if(3==a.g){var b=a.Nl++,c=a.In.clone();g.Jm(c,"SID",a.o);g.Jm(c,"RID",b);g.Jm(c,"TYPE","terminate");T6(a,c);b=new D6(a,a.o,b,void 0);b.Bj=2;b.lh=f6(c.clone());(new window.Image).src=b.lh;b.gk=(0,g.G)();F6(b)}EBa(a)},GBa=function(a){a.vI(1,0);
a.In=P6(a,null,a.sr);U6(a)},DBa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.rg&&(g.w.clearTimeout(a.rg),a.rg=null);V6(a);a.Wd&&(a.Wd.cancel(),a.Wd=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},HBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new zBa(a.SO++,b));2!=a.g&&3!=a.g||U6(a)},U6=function(a){a.Wd||a.eh||(a.eh=M6((0,g.z)(a.pC,a),0),a.tj=0)},JBa=function(a,b){if(1==a.g){if(!b){a.Nl=Math.floor(1E5*Math.random());
var c=a.Nl++,d=new D6(a,"",c,void 0);d.mi=null;var e=W6(a),f=a.In.clone();g.Jm(f,"RID",c);g.Jm(f,"CVER","1");T6(a,f);oBa(d,f,e);a.Wd=d;a.g=2}}else 3==a.g&&(b?IBa(a,b):0==a.l.length||a.Wd||IBa(a))},IBa=function(a,b){if(b)if(6<a.Yh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Nl-1;var d=W6(a)}else c=b.F,d=b.Mi;else c=a.Nl++,d=W6(a);var e=a.In.clone();g.Jm(e,"SID",a.o);g.Jm(e,"RID",c);g.Jm(e,"AID",a.Pj);T6(a,e);c=new D6(a,a.o,c,a.tj+1);c.mi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wd=c;oBa(c,e,d)},T6=function(a,b){if(a.sd){var c=a.sd.by();
c&&g.Kb(c,function(a,c){g.Jm(b,c,a)})}},W6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Yh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Yh?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},KBa=function(a){a.wc||a.rg||(a.D=1,a.rg=M6((0,g.z)(a.oC,a),0),a.gj=0)},X6=function(a){if(a.wc||a.rg||3<=a.gj)return!1;
a.D++;a.rg=M6((0,g.z)(a.oC,a),LBa(a,a.gj));a.gj++;return!0},Q6=function(a,b,c){a.Np=c;
a.Nf=b.zg;a.C||GBa(a)},V6=function(a){null!=a.bi&&(g.w.clearTimeout(a.bi),a.bi=null)},LBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Y6=function(a,b){if(2==b||9==b){var c=null;
a.sd&&(c=null);var d=(0,g.z)(a.RU,a);c||(c=new g.Am("//www.google.com/images/cleardot.gif"),f6(c));vBa(c.toString(),1E4,d)}else H6(2);MBa(a,b)},MBa=function(a,b){a.g=0;
a.sd&&a.sd.Vw(b);EBa(a);DBa(a)},EBa=function(a){a.g=0;
a.Nf=-1;if(a.sd)if(0==a.A.length&&0==a.l.length)a.sd.Eq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.sd.Eq(b)}},P6=function(a,b,c){var d=g.Km(c);
if(""!=d.l)b&&g.Cm(d,b+"."+d.l),g.Dm(d,d.B);else{var e=window.location;d=MAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Qk&&g.Kb(a.Qk,function(a,b){g.Jm(d,b,a)});
g.Jm(d,"VER",a.Yh);T6(a,d);return d},M6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},H6=function(a){Z6.dispatchEvent(new ABa(Z6,a))},NBa=function(){},OBa=function(a,b){this.action=a;
this.params=b||{}},$6=function(a,b){g.L.call(this);
this.g=new g.Yt(this.US,0,this);g.M(this,this.g);this.dd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},a7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.SC;this.l=new $6(this.wV,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},PBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Np,sessionId:a.g.o,arrayId:a.g.Pj}},QBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&JBa(a.g),FBa(a.g));a.F=0},b7=function(a){return!!a.g&&3==a.g.g},RBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},c7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Jg(a)||"";b&&(this.port=":"+b);this.domain=g.Ig(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},d7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Sg(c+b,{})},e7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Jb:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),yd:g.Fa(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.pE(b,a)},VBa=function(){var a=SBa;
TBa();f7.push(a);UBa(f7)},g7=function(a,b){TBa();
var c=f7,d=WBa(a,String(b));g.Qa(c)?XBa(d):(UBa(c),(0,g.B)(c,function(a){a(d)}))},TBa=function(){f7||(f7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",f7,void 0))},XBa=function(a){var b=(h7+1)%50;
h7=b;i7[b]=a;j7||(j7=49==b)},UBa=function(a){var b=i7;
if(b[0]){var c=h7,d=j7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
i7=Array(50);h7=-1;j7=!1}},WBa=function(a,b){var c=((0,g.G)()-YBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},k7=function(a){g.IF.call(this);
this.D=a;this.g=[]},ZBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},$Ba=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!n6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=ZBa(a,b[d])||c;return c},aCa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},l7=function(a,b,c,d){g.IF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},n7=function(a){k7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;m7(this);this.info("Initializing with "+l6(this.g))},bCa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=d7(a.o,"/pairing/get_lounge_token_batch");
e7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.dJ,a),(0,g.z)(a.cJ,a))}},m7=function(a){var b=UAa($Aa());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return $Ba(a,b)},o7=function(a,b){bBa((0,g.H)(a.g,SAa));
b&&aBa()},q7=function(a,b){g.IF.call(this);
this.C=b;var c=g.PG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.C(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;p7("Initialized with "+g.zg(this.g))},cCa=function(a,b,c){var d=d7(a.B,"/pairing/get_screen_availability");
e7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},r7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(p7("Updated online screens: "+g.zg(a.g)),a.g=b,a.R("screenChange"));dCa(a)},s7=function(a){(0,window.isNaN)(a.o)||g.UD(a.o);
a.o=g.SD((0,g.z)(a.qu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},p7=function(a){g7("OnlineScreenService",a)},eCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},dCa=function(a){a=g.Sb(g.Lb(a.g,function(a){return a}));
g.ib(a);a.length?g.OG("yt-remote-online-screen-ids",a.join(","),60):g.QG("yt-remote-online-screen-ids")},t7=function(a){k7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};fCa(this)},hCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.oe();if(k=(c?o6(k,c):null)||o6(k,b)){k.uuid=b;var l=u7(a,k);cCa(a.l,l,function(a){e(a?l:null)})}else c?gCa(a,c,(0,g.z)(function(a){var f=u7(this,new i6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));cCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},iCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},gCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,Jb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.pE(d7(a.C,"/pairing/get_lounge_token_batch"),e)},jCa=function(a){a.g=a.o.oe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+l6(a.g))},fCa=function(a){v7(a);
a.o=new n7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.sJ,a));jCa(a);a.A=UAa(g.PG("yt-remote-automatic-screen-cache")||[]);v7(a);a.info("Initializing automatic screens: "+l6(a.A));a.l=new q7(a.C,(0,g.z)(a.oe,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},u7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=o6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.OG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,SAa)));v7(a);a.B[b.uuid]=b.id;g.OG("yt-remote-device-id-map",a.B,31536E3);return b},v7=function(a){a.B=g.PG("yt-remote-device-id-map")||{}},w7=function(a,b,c){g.IF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},x7=function(a,b){g7(a.M,b)},y7=function(a,b){w7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.CV,this);this.B=(0,g.z)(this.GT,this);this.A=g.SD((0,g.z)(function(){kCa(this,null)},this),12E4)},lCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.zg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){x7(this,"Failed to send message: getMdxSessionStatus.")},a)):x7(a,"Sending yt message without session: "+g.zg(b))},kCa=function(a,b){g.UD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.So,a),d=(0,g.z)(a.we,a);a.qy(b,c,d,5)}}else a.we(Error("Waiting for session status timed out."))},z7=function(a,b,c){w7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.GV,this);this.g=g.y},mCa=function(a){a.g=a.H.BE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.So(a)},a),(0,g.z)(function(a){this.g=g.y;
this.we(a)},a))},nCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}dBa()&&(b.env_useStageMdx=1);return g.Qg(b)},A7=function(a,b){w7.call(this,a,b,"ManualSession");
this.g=g.SD((0,g.z)(this.Qj,this,null),150)},B7=function(a,b,c,d){g.IF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.hS,this)},oCa=function(a,b){return b?g.Ma(a.o,function(a){return j6(b,a.label)},a):null},C7=function(a){g7("Controller",a)},SBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},D7=function(a){return a.B||!!a.o.length||!!a.g},E7=function(a,b,c){b!=a.g&&(g.af(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.mC,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Qj(null)):a.R("yt-remote-cast2-session-change",null))},pCa=function(a){var b=a.l.AE(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&j6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=oCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},vCa=function(a,b,c,d,e,f,k){qCa()?rCa(b,e,f,k)&&(G7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?sCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?sCa(a,c):(H7("Failed to load cast API: "+d),I7(!1),G7(!1),g.QG("yt-remote-cast-available"),g.QG("yt-remote-cast-receiver"),tCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):gBa():z6("CriOS")?lBa():z6("Android")&&z6("Chrome/")&&window.navigator.presentation?mBa():window.chrome&&window.navigator.presentation&&!z6("Edge")?(A6(),w6(uCa.map(jBa))):x6())):F7("Cannot initialize because not running Chrome")},tCa=function(){F7("dispose");
var a=J7();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);wCa(!1);g.VF(K7);K7.length=0},L7=function(){return!!g.PG("yt-remote-cast-installed")},xCa=function(){var a=g.PG("yt-remote-cast-receiver");
return a?a.friendlyName:null},yCa=function(){F7("clearCurrentReceiver");
g.QG("yt-remote-cast-receiver")},zCa=function(){return L7()?J7()?J7().getCastSession():(H7("getCastSelector: Cast is not initialized."),null):(H7("getCastSelector: Cast API is not installed!"),null)},N7=function(){L7()?J7()?M7()?(F7("Requesting cast selector."),J7().requestSession()):(F7("Wait for cast API to be ready to request the session."),K7.push(g.UF("yt-remote-cast2-api-ready",N7))):H7("requestCastSelector: Cast is not initialized."):H7("requestCastSelector: Cast API is not installed!")},O7=
function(a,b){M7()?J7().setConnectedScreenStatus(a,b):H7("setConnectedScreenStatus called before ready.")},qCa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.OJ||a},ACa=function(a,b){J7().init(a,b)},rCa=function(a,b,c,d){var e=!1;
J7()||(a=new B7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.OG("yt-remote-cast-available",a);g.YF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){F7("onReceiverSelected: "+a.friendlyName);
g.OG("yt-remote-cast-receiver",a);g.YF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){F7("onReceiverResumed: "+a.friendlyName);
g.OG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){F7("onSessionChange: "+k6(a));
a||g.QG("yt-remote-cast-receiver");g.YF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
F7("cloudview.createSingleton_: "+e);return e},J7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},sCa=function(a,b){I7(!0);
G7(!1);ACa(a,function(a){a?(wCa(!0),g.XF("yt-remote-cast2-api-ready")):(H7("Failed to initialize cast API."),I7(!1),g.QG("yt-remote-cast-available"),g.QG("yt-remote-cast-receiver"),tCa());b(a)})},F7=function(a){g7("cloudview",a)},H7=function(a){g7("cloudview",a)},I7=function(a){F7("setCastInstalled_ "+a);
g.OG("yt-remote-cast-installed",a)},M7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},wCa=function(a){F7("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},G7=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},P7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Qf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},Q7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Qf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},R7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},S7=function(a,b){a.F=b;
a.D=(0,g.G)()},T7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},U7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&Q7(a)},V7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Qf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},X7=function(a,b){g.IF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.iC;this.o=this.l=null;this.H=(0,g.z)(this.CP,this);this.D=(0,g.z)(this.Ql,this);this.F=(0,g.z)(this.BP,this);this.I=(0,g.z)(this.PP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.vv,this),BCa(this))):c=3;0!=c&&(b?this.vv(c):g.SD((0,g.z)(function(){this.vv(c)},this),0));
var d=zCa();d&&W7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},Y7=function(a){return new P7(a.A.getPlayerContextData())},BCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.dS,a),this))},a)},CCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},Z7=function(a,b){50>a.B.Fc()&&g.kC(a.B,b)},a8=function(a,b,c){var d=Y7(a);
S7(d,c);-1E3!=d.g&&(d.g=b);$7(a,d)},b8=function(a,b,c){a.A.sendMessage(b,c)},$7=function(a,b){CCa(a);
a.A.setPlayerContextData(V7(b));BCa(a)},W7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Ql(null));
a.o=b;a.o&&(g7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Ql(a.o.media[0]))},DCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=Y7(a);b.contentId!=d.videoId&&g7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;S7(d,a.l.getEstimatedTime());$7(a,d)}else g7("CP","No cast media video. Ignoring state update.")},c8=function(a,b,c){return(0,g.z)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),b8(this,b,c))},a)},d8=function(a,b,c){g.IF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.P=[];this.A=this.D=this.o=this.Za=this.g=null;this.oa=a;this.P.push(g.sF(window,"beforeunload",(0,g.z)(this.TI,this)));this.l=[];this.Za=new P7;this.X=b.id;this.g=ECa(this,c);this.g.subscribe("handlerOpened",this.GP,this);this.g.subscribe("handlerClosed",this.DP,this);this.g.subscribe("handlerError",this.EP,this);this.g.subscribe("handlerMessage",this.FP,this);RBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.RG()&&g.OG("yt-remote-session-video-id",a)},this)},e8=function(a){g7("conn",a)},ECa=function(a,b){return new a7(d7(a.oa,"/bc"),b)},f8=function(a,b){a.R("proxyStateChange",b)},FCa=function(a){a.B=g.SD((0,g.z)(function(){e8("Connecting timeout");
this.C(1)},a),2E4)},g8=function(a){g.UD(a.B);
a.B=window.NaN},h8=function(a){g.UD(a.M);
a.M=window.NaN},GCa=function(a){i8(a);
a.K=g.SD((0,g.z)(function(){j8(this,"getNowPlaying")},a),2E4)},i8=function(a){g.UD(a.K);
a.K=window.NaN},ICa=function(a,b){b&&(g8(a),h8(a));
b==(b7(a.g)&&(0,window.isNaN)(a.B))?b&&(f8(a,1),j8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),f8(a,1),j8(a,"getNowPlaying"),HCa(a)):a.C(1)},JCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Yb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},KCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;U7(a.Za,c,d);a.R("remoteQueueChange")},MCa=function(a,b){b.params=b.params||{};
KCa(a,b);LCa(a,b);a.R("autoplayDismissed")},LCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
S7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?GCa(a):i8(a);
a.R("remotePlayerChange")},NCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);S7(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},OCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},PCa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},QCa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Qf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},HCa=function(a){g.UD(a.I);
a.I=g.SD((0,g.z)(a.C,a,1),864E5)},j8=function(a,b,c){c?e8("Sending: action="+b+", params="+g.zg(c)):e8("Sending: action="+b);
a.g.sendMessage(b,c)},k8=function(a){k7.call(this,"ScreenServiceProxy");
this.cd=a;this.l=[];this.l.push(this.cd.$_s("screenChange",(0,g.z)(this.AV,this)));this.l.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.ER,this)))},VCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.MD("MDX_CONFIG")||b;WAa();s6();l8||(l8=new c7(b?b.loungeApiHost:void 0),dBa()&&(l8.g="/api/loungedev"));m8||(m8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",m8,void 0));RCa();var c=n8();if(!c){var d=new t7(l8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=n8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);vCa(a,d,function(a){a?o8()&&O7(o8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.YF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),p8("Initializing: "+g.zg(b)),q8.push(g.UF("yt-remote-cast2-availability-change",function(){g.YF("yt-remote-receiver-availability-change")})),q8.push(g.UF("yt-remote-cast2-receiver-selected",function(){r8(null);
g.YF("yt-remote-auto-connect","cast-selector-receiver")})),q8.push(g.UF("yt-remote-cast2-receiver-resumed",function(){g.YF("yt-remote-receiver-resumed","cast-selector-receiver")})),q8.push(g.UF("yt-remote-cast2-session-change",SCa)),q8.push(g.UF("yt-remote-connection-change",function(a){a?O7(o8(),"YouTube TV"):s8()||(O7(null,null),yCa())})),a=t8(),b.isAuto&&(a.id+="#dial"),g.OF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),p8(" -- with channel params: "+
g.zg(a)),TCa(a),c.start(),o8()||UCa())},XCa=function(){var a=WCa();
L7()&&g.PG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},WCa=function(){var a=n8().cd.$_gos();
var b=u8();b&&v8()&&(n6(a,b)||a.push(b));return VAa(a)},w8=function(){var a=YCa();
!a&&L7()&&xCa()&&(a={key:"cast-selector-receiver",name:xCa()});return a},YCa=function(){var a=WCa(),b=u8();
b||(b=s8());return g.Ma(a,function(a){return b&&j6(b,a.key)?!0:!1})},u8=function(){var a=o8();
if(!a)return null;var b=n8().oe();return o6(b,a)},SCa=function(a){p8("remote.onCastSessionChange_: "+k6(a));
if(a){var b=u8();b&&b.id==a.id?O7(b.id,"YouTube TV"):(b&&x8(),y8(a,1))}else v8()&&x8()},x8=function(){M7()?J7().stopSession():H7("stopSession called before API ready.");
var a=v8();a&&(a.disconnect(1),z8(null))},A8=function(){var a=v8();
return!!a&&3!=a.getProxyState()},p8=function(a){g7("remote",a)},n8=function(){if(!B8){var a=g.x("yt.mdx.remote.screenService_");
B8=a?new k8(a):null}return B8},o8=function(){return g.x("yt.mdx.remote.currentScreenId_")},ZCa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},$Ca=function(){return g.x("yt.mdx.remote.connectData_")},r8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},v8=function(){return g.x("yt.mdx.remote.connection_")},z8=function(a){var b=v8();
r8(null);a||ZCa("");g.wa("yt.mdx.remote.connection_",a,void 0);m8&&((0,g.B)(m8,function(b){b(a)}),m8.length=0);
b&&!a?g.YF("yt-remote-connection-change",!1):!b&&a&&g.YF("yt-remote-connection-change",!0)},s8=function(){var a=g.RG();
if(!a)return null;var b=n8().oe();return o6(b,a)},y8=function(a,b){u8()&&u8();
ZCa(a.id);var c=new d8(l8,a,t8());c.connect(b,$Ca());c.subscribe("beforeDisconnect",function(a){g.YF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){v8()&&z8(null)});
z8(c)},UCa=function(){var a=s8();
a?(p8("Resume connection to: "+k6(a)),y8(a,0)):(t6(),yCa(),p8("Skipping connecting because no session screen found."))},RCa=function(){var a=t8();
if(g.Yb(a)){a=r6();var b=g.PG("yt-remote-session-name")||"",c=g.PG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},t8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},TCa=function(a){a?(g.OG("yt-remote-session-app",a.app),g.OG("yt-remote-session-name",a.name)):(g.QG("yt-remote-session-app"),g.QG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},C8=function(a,b,c){g.L.call(this);
this.F=a;this.l=b;this.o=new g.FF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.VQ);this.o.O(b,"captionschanged",this.AP);this.o.O(b,"captionssettingschanged",this.JD);this.o.O(b,"videoplayerreset",this.To);this.o.O(b,"mdxautoplaycancel",this.ZH);this.P=this.o.O(b,"onVolumeChange",this.WB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.jC,this);c.subscribe("remotePlayerChange",this.Tl,this);c.subscribe("remoteQueueChange",this.To,this);c.subscribe("autoplayUpNext",this.GB,
this);c.subscribe("previousNextChange",this.gC,this);c.subscribe("nowAutoplaying",this.YB,this);c.subscribe("autoplayDismissed",this.FB,this);this.suggestion=null;this.H=new g.VO(64);this.A=new g.Yt(this.FD,500,this);g.M(this,this.A);this.B=new g.Yt(this.GD,1E3,this);g.M(this,this.B);this.K=new B6(this.dV,0,this);g.M(this,this.K);this.C={};this.M=new g.Yt(this.lE,1E3,this);g.M(this,this.M);this.I=new g.Uk(this.FN,1E3,this);g.M(this,this.I);this.N=g.y;this.JD();this.To();this.Tl()},D8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},aDa=function(a){D8(a,0);
a.A.stop();E8(a,new g.VO(64))},G8=function(a,b){if(F8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Fi()},g.ec(c,b));a.g.xD(a.l.ea(1).videoId,c);a.C=Y7(a.g).l}},H8=function(a,b){var c=a.l.ag();
if(c){var d=c.je();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Lj;var m=Y7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};U7(m,k,l);g.t(b)&&(S7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);b8(c,"setPlaylist",q);e||$7(c,m);E8(a,new g.VO(1))},bDa=function(a,b){if(b){var c=a.l.Ac("captions","tracklist",{kz:1});
c&&c.length?(a.l.Ld("captions","track",b),a.D=!1):(a.l.Tj("captions"),a.D=!0)}else a.l.Ld("captions","track",{})},F8=function(a){return Y7(a.g).videoId==a.l.ea(1).videoId},E8=function(a,b){a.B.stop();
var c=a.H;if(!g.cP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.XU(a.l,d);a.H=b;cDa(a.F,c,b)}},I8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.soa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.DV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);dDa(this,g.UU(a))},dDa=function(a,b){if(3==a.o.Sa()){var c={RECEIVER_NAME:a.o.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},J8=function(a,b){g.LZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},K8=function(a){g.rV.call(this,a);
g.TG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:m6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.VO(64);this.H=0;if(!g.zM(g.Y(this.g))){a=
this.g;var b=g.hI(a);b&&(b=b.zo())&&(b=new J8(a,b),g.M(this,b));b=new I8(a);g.M(this,b);g.lV(a,b.element,4)}},cDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.iP(c,b))},L8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)x8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.ag();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Lj,index:Math.max(a.g.lA(),0),currentTime:0==f?void 0:f}}else c=null;p8("Connecting to: "+g.zg(b));"cast-selector-receiver"==b.key?(r8(c||null),M7()?J7().setLaunchParams(c||null):H7("setLaunchParams called before ready.")):!c&&
A8()&&o8()==b.key?g.YF("yt-remote-connection-change",!0):(x8(),r8(c||null),c=n8().oe(),(c=o6(c,b.key))&&y8(c,1))}},sBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},L6={"'":"\\'"},eDa={},RAa={SW:"atp",l1:"ska",B0:"que",N_:"mus",g1:"sus",bZ:"dsp"};
h6.prototype.sn=function(){var a=new h6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var u6,q6="",y6=v6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",kBa=v6("loadCastFramework")||v6("loadCastApplicationFramework"),uCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(B6,g.L);g.h=B6.prototype;g.h.NI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.dd:this.xa=g.tg(this.B,this.dd)};
g.h.stop=function(){this.xa&&(g.ug(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();B6.Z.V.call(this)};
g.h.OI=function(){this.o?(this.xa=g.tg(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};C6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
C6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=D6.prototype;g.h.mi=null;g.h.yf=!1;g.h.Ak=null;g.h.lv=null;g.h.gk=null;g.h.Bj=null;g.h.lh=null;g.h.Eh=null;g.h.Mi=null;g.h.Rc=null;g.h.lm=0;g.h.zf=null;g.h.Op=null;g.h.mh=null;g.h.jl=-1;g.h.eD=!0;g.h.Wh=!1;g.h.wr=0;g.h.fp=null;var qBa={},G6={};g.h=D6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.aU=function(a){a=a.target;var b=this.fp;b&&3==g.ix(a)?b.zj():this.uE(a)};
g.h.uE=function(a){try{if(a==this.Rc)a:{var b=g.ix(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.wd&&!g.rc(10)||g.yd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ef&&!g.ox(this.Rc))break a;this.Wh||4!=b||7==c||(8==c||0>=d?this.g.sf(3):this.g.sf(2));N6(this);var e=this.Rc.getStatus();this.jl=e;var f=g.ox(this.Rc);(this.yf=200==e)?(4==b&&J6(this),this.C?(rBa(this,b,f),g.ef&&this.yf&&3==b&&(this.A.T(this.l,"tick",this.UT),this.l.start())):I6(this,f),this.yf&&!this.Wh&&(4==b?this.g.Ro(this):
(this.yf=!1,F6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mh=3,H6(13)):(this.mh=0,H6(14)),J6(this),K6(this))}}catch(k){this.Rc&&g.ox(this.Rc)}finally{}};
g.h.UT=function(){var a=g.ix(this.Rc),b=g.ox(this.Rc);this.lm<b.length&&(N6(this),rBa(this,a,b),this.yf&&4!=a&&F6(this))};
g.h.dT=function(a){M6((0,g.z)(this.cT,this,a),0)};
g.h.cT=function(a){this.Wh||(N6(this),I6(this,a),F6(this))};
g.h.rC=function(a){M6((0,g.z)(this.bT,this,a),0)};
g.h.bT=function(a){this.Wh||(J6(this),this.yf=a,this.g.Ro(this),this.g.sf(4))};
g.h.cancel=function(){this.Wh=!0;J6(this)};
g.h.uT=function(){this.Ak=null;var a=(0,g.G)();0<=a-this.lv?(2!=this.Bj&&this.g.sf(3),J6(this),this.mh=2,H6(18),K6(this)):uBa(this,this.lv-a)};g.h=xBa.prototype;g.h.tr=null;g.h.xe=null;g.h.gp=!1;g.h.Ay=null;g.h.Fn=null;g.h.ur=null;g.h.vr=null;g.h.Ne=null;g.h.zg=-1;g.h.il=null;g.h.Fk=null;g.h.connect=function(a){this.vr=a;a=P6(this.g,null,this.vr);H6(3);this.Ay=(0,g.G)();var b=this.g.F;null!=b?(this.il=b[0],(this.Fk=b[1])?(this.Ne=1,yBa(this)):(this.Ne=2,R6(this))):(g6(a,"MODE","init"),this.xe=new D6(this,void 0,void 0,void 0),this.xe.mi=this.tr,E6(this.xe,a,!1,null,!0),this.Ne=0)};
g.h.aI=function(a){if(a)this.Ne=2,R6(this);else{H6(4);var b=this.g;b.Nf=b.ah.zg;Y6(b,9)}a&&this.sf(2)};
g.h.Pq=function(a){return this.g.Pq(a)};
g.h.abort=function(){this.xe&&(this.xe.cancel(),this.xe=null);this.zg=-1};
g.h.zy=function(){return!1};
g.h.kC=function(a,b){this.zg=a.jl;if(0==this.Ne)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Nf=this.zg;Y6(c,2);return}this.il=c[0];this.Fk=c[1]}else c=this.g,c.Nf=this.zg,Y6(c,2);else if(2==this.Ne)if(this.gp)H6(7),this.ur=(0,g.G)();else if("11111"==b){if(H6(6),this.gp=!0,this.Fn=(0,g.G)(),c=this.Fn-this.Ay,!g.wd||g.rc(10)||500>c)this.zg=200,this.xe.cancel(),H6(12),Q6(this.g,this,!0)}else H6(8),this.Fn=this.ur=(0,g.G)(),this.gp=!1};
g.h.Ro=function(){this.zg=this.xe.jl;if(this.xe.yf)0==this.Ne?this.Fk?(this.Ne=1,yBa(this)):(this.Ne=2,R6(this)):2==this.Ne&&((!g.wd||g.rc(10)?!this.gp:200>this.ur-this.Fn)?(H6(11),Q6(this.g,this,!1)):(H6(12),Q6(this.g,this,!0)));else{0==this.Ne?H6(9):2==this.Ne&&H6(10);var a=this.g;a.Nf=this.zg;Y6(a,2)}};
g.h.fm=function(){return this.g.fm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.sf=function(a){this.g.sf(a)};g.h=S6.prototype;g.h.Qk=null;g.h.Wd=null;g.h.wc=null;g.h.sr=null;g.h.In=null;g.h.Lw=null;g.h.Xn=null;g.h.Nl=0;g.h.SO=0;g.h.sd=null;g.h.eh=null;g.h.rg=null;g.h.bi=null;g.h.ah=null;g.h.Np=null;g.h.Pj=-1;g.h.zz=-1;g.h.Nf=-1;g.h.tj=0;g.h.gj=0;g.h.Yh=8;var Z6=new g.Ef;g.A(ABa,g.cf);g.A(BBa,g.cf);g.A(CBa,g.cf);g.h=S6.prototype;g.h.connect=function(a,b,c,d,e){H6(0);this.sr=b;this.Qk=c||{};d&&g.t(e)&&(this.Qk.OSID=d,this.Qk.OAID=e);this.C?(M6((0,g.z)(this.mx,this,a),100),GBa(this)):this.mx(a)};
g.h.mx=function(a){this.ah=new xBa(this);this.ah.tr=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.zy=function(){return 0==this.g};
g.h.pC=function(a){this.eh=null;JBa(this,a)};
g.h.oC=function(){this.rg=null;this.wc=new D6(this,this.o,"rpc",this.D);this.wc.mi=null;this.wc.wr=0;var a=this.Lw.clone();g.Jm(a,"RID","rpc");g.Jm(a,"SID",this.o);g.Jm(a,"CI",this.Np?"0":"1");g.Jm(a,"AID",this.Pj);T6(this,a);if(!g.wd||g.rc(10))g.Jm(a,"TYPE","xmlhttp"),E6(this.wc,a,!0,this.Xn,!1);else{g.Jm(a,"TYPE","html");var b=this.wc,c=!!this.Xn;b.Bj=3;b.lh=f6(a.clone());tBa(b,c)}};
g.h.kC=function(a,b){if(0!=this.g&&(this.wc==a||this.Wd==a))if(this.Nf=a.jl,this.Wd==a&&3==this.g)if(7<this.Yh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.rg){if(this.wc)if(this.wc.gk+3E3<this.Wd.gk)V6(this),this.wc.cancel(),this.wc=null;else break a;X6(this);H6(19)}}else this.zz=c[1],0<this.zz-this.Pj&&37500>c[2]&&this.Np&&0==this.gj&&!this.bi&&(this.bi=M6((0,g.z)(this.vP,this),6E3));else Y6(this,11)}else b!=eDa.WX.g&&Y6(this,11);else if(this.wc==a&&
V6(this),!g.E(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Pj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Xn=e[2],e=e[3],null!=e?this.Yh=e:this.Yh=6,this.g=3,this.sd&&this.sd.Xw(),this.Lw=P6(this,this.fm()?this.Xn:null,this.sr),KBa(this)):"stop"==e[0]&&Y6(this,7):3==this.g&&("stop"==e[0]?Y6(this,7):"noop"!=e[0]&&this.sd&&this.sd.Ww(e),this.gj=0)}}};
g.h.vP=function(){null!=this.bi&&(this.bi=null,this.wc.cancel(),this.wc=null,X6(this),H6(20))};
g.h.Ro=function(a){if(this.wc==a){V6(this);this.wc=null;var b=2}else if(this.Wd==a)this.Wd=null,b=1;else return;this.Nf=a.jl;if(0!=this.g)if(a.yf)1==b?(b=(0,g.G)()-a.gk,Z6.dispatchEvent(new BBa(Z6,a.Mi?a.Mi.length:0,b,this.tj)),U6(this),this.A.length=0):KBa(this);else{var c=a.mh,d;if(!(d=3==c||7==c||0==c&&0<this.Nf)){if(d=1==b)this.Wd||this.eh||1==this.g||2<=this.tj?d=!1:(this.eh=M6((0,g.z)(this.pC,this,a),LBa(this,this.tj)),this.tj++,d=!0);d=!(d||2==b&&X6(this))}if(d)switch(c){case 1:Y6(this,5);
break;case 4:Y6(this,10);break;case 3:Y6(this,6);break;case 7:Y6(this,12);break;default:Y6(this,2)}}};
g.h.vI=function(a){if(!g.C(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.RU=function(a){a?H6(2):(H6(1),MBa(this,8))};
g.h.Pq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.cx;a.F=!1;return a};
g.h.isActive=function(){return!!this.sd&&this.sd.isActive(this)};
g.h.sf=function(a){Z6.dispatchEvent(new CBa(Z6,a))};
g.h.fm=function(){return!(!g.wd||g.rc(10))};
g.h=NBa.prototype;g.h.Xw=function(){};
g.h.Ww=function(){};
g.h.Vw=function(){};
g.h.Eq=function(){};
g.h.by=function(){return{}};
g.h.isActive=function(){return!0};g.A($6,g.L);g.h=$6.prototype;g.h.US=function(){this.dd=Math.min(3E5,2*this.dd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.dd+15E3*Math.random();g.Zt(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.dd=5E3};g.A(a7,NBa);g.h=a7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Od=function(a){return this.o.Od(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.af(this.o),QBa(this),g.af(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new S6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.sd=null);d.sd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Pj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):b7(this)&&HBa(this.g,c)};
g.h.Xw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)HBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Vw=function(a){var b=2==a&&401==this.g.Nf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.Eq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.by=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.Ww=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),FBa(this.g)):this.R("handlerMessage",new OBa(a[0],a[1]))};
g.h.wV=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Wd&&b++;0!=b||this.connect(this.B,this.A)};c7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
c7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
c7.prototype.B=function(a){a(Error("request timed out"))};var YBa=(0,g.G)(),f7=null,i7=Array(50),h7=-1,j7=!1;g.A(k7,g.IF);k7.prototype.oe=function(){return this.g};
k7.prototype.contains=function(a){return!!n6(this.g,a)};
k7.prototype.get=function(a){return a?o6(this.g,a):null};
k7.prototype.info=function(a){g7(this.D,a)};g.A(l7,g.IF);var fDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=l7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.zE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.UD(this.xa),this.xa=window.NaN)};
g.h.V=function(){this.stop();l7.Z.V.call(this)};
g.h.zE=function(){this.xa=window.NaN;this.g=g.pE(d7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,Jb:(0,g.z)(this.yV,this),onError:(0,g.z)(this.xV,this),yd:(0,g.z)(this.zV,this)})};
g.h.yV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new i6(c))};
g.h.xV=function(a){this.g=null;a.status&&404==a.status?this.l>=fDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=fDa[this.l],this.xa=g.SD((0,g.z)(this.zE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.zV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(n7,k7);g.h=n7.prototype;g.h.start=function(){m7(this)&&this.R("screenChange");!g.PG("yt-remote-lounge-token-expiration")&&bCa(this);g.UD(this.l);this.l=g.SD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){m7(this);ZBa(this,a);o7(this,!1);this.R("screenChange");b(a);a.token||bCa(this)};
g.h.remove=function(a,b){var c=m7(this);aCa(this,a)&&(o7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Jp=function(a,b,c,d){var e=m7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,o7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.UD(this.l);n7.Z.V.call(this)};
g.h.dJ=function(a){m7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}o7(this,!b);b&&g7(this.D,"Missed "+b+" lounge tokens.")};
g.h.cJ=function(a){g7(this.D,"Requesting lounge tokens failed: "+a)};g.A(q7,g.IF);g.h=q7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.PG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?s7(this):(this.A=(0,g.G)()+3E5,g.OG("yt-remote-fast-check-period",this.A),this.qu())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){p7("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!o6(a,d)},this);
r7(this,b)};
g.h.V=function(){g.UD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);q7.Z.V.call(this)};
g.h.qu=function(){g.UD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=eCa(this);if(g.Pb(a)){var b=d7(this.B,"/pairing/get_screen_availability");this.l=e7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.BS,this,a),(0,g.z)(this.AS,this))}else r7(this,{}),s7(this)};
g.h.BS=function(a,b){this.l=null;var c=g.Sb(eCa(this));if(g.jb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;r7(this,d);s7(this)}else this.hc("Changing Screen set during request."),this.qu()};
g.h.AS=function(a){this.hc("Screen availability failed: "+a);this.l=null;s7(this)};
g.h.hc=function(a){g7("OnlineScreenService",a)};g.A(t7,k7);g.h=t7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Jp=function(a,b,c,d){this.o.contains(a)?this.o.Jp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,g7(this.D,a),d(Error(a)))};
g.h.oe=function(a){return a?this.g:g.Wa(this.g,(0,g.Jd)(this.A,function(a){return!this.contains(a)},this))};
g.h.AE=function(){return(0,g.Jd)(this.oe(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.BE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new l7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.af(f);d(u7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.af(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.BV=function(a,b,c,d){g.pE(d7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,Jb:(0,g.z)(function(a,d){var e=new i6(d.screen||{});if(!e.name||iCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);iCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(u7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
yd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.af(this.o);g.af(this.l);t7.Z.V.call(this)};
g.h.sJ=function(){jCa(this);this.R("screenChange");this.l.update()};
t7.prototype.dispose=t7.prototype.dispose;g.A(w7,g.IF);g.h=w7.prototype;g.h.So=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.we=function(a){this.ha()||(a&&x7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){g7(this.M,a)};
g.h.DE=function(){return null};
g.h.Au=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){x7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Au("");w7.Z.V.call(this)};g.A(y7,w7);g.h=y7.prototype;g.h.zu=function(a){if(this.g){if(this.g==a)return;x7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);lCa(this)};
g.h.Qj=function(a){this.info("launchWithParams no-op for Cast: "+g.zg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.we()},this),(0,g.z)(function(){this.we(Error("Failed to stop receiver app."))},this)):this.we(Error("Stopping cast device witout session."))};
g.h.Au=g.y;g.h.V=function(){this.info("disposeInternal");g.UD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;y7.Z.V.call(this)};
g.h.GT=function(a,b){if(!this.ha())if(b){var c=g.Xw(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.zg(c));switch(d){case "mdxSessionStatus":kCa(this,c.screenId);break;default:x7(this,"Unknown youtube message: "+d)}}else x7(this,"Unable to parse message.")}else x7(this,"No data in message.")};
g.h.qy=function(a,b,c,d){hCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(x7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.SD((0,g.z)(this.qy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.DE=function(){return this.g};
g.h.CV=function(a){this.ha()||a||(x7(this,"Cast session died."),this.we())};g.A(z7,w7);g.h=z7.prototype;g.h.zu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Qj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.UD(this.C);this.A?this.A.stop((0,g.z)(this.we,this,null),(0,g.z)(this.we,this,"Failed to stop DIAL device.")):this.we()};
g.h.V=function(){this.g();this.g=g.y;g.UD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;z7.Z.V.call(this)};
g.h.GV=function(a){this.ha()||a||(x7(this,"DIAL session died."),this.g(),this.g=g.y,this.we())};
g.h.ks=function(a){this.I=m6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,nCa(this));a(b);mCa(this)}else this.D=(0,g.z)(function(){g.UD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,nCa(this));a(b);mCa(this)},this),this.C=g.SD((0,g.z)(function(){this.D()},this),100)};
g.h.GK=function(a,b,c){hCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.So(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ks(b,c)},this),(0,g.z)(function(a){x7(this,"Failed to get DIAL screen: "+a);
this.ks(b,c)},this))};g.A(A7,w7);A7.prototype.stop=function(){this.we()};
A7.prototype.zu=g.y;A7.prototype.Qj=function(){g.UD(this.g);this.g=window.NaN;var a=o6(this.H.oe(),this.l.label);a?this.So(a):this.we(Error("No such screen"))};
A7.prototype.V=function(){g.UD(this.g);this.g=window.NaN;A7.Z.V.call(this)};g.A(B7,g.IF);g.h=B7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.lC,this),(0,g.z)(this.lS,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.gQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),VBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.CE,this)),this.o=pCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.hc("Failed to set initial custom receivers: "+g.zg(a))},this)),this.R("yt-remote-cast2-availability-change",D7(this)),b(!0))},this),(0,g.z)(function(a){this.hc("Failed to initialize API: "+g.zg(a));
b(!1)},this))};
g.h.BU=function(a,b){C7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)C7("Unsetting old screen status: "+this.g.l.friendlyName),E7(this,null)}if(a&&b){if(!this.g){c=o6(this.l.oe(),a);if(!c){C7("setConnectedScreenStatus: Unknown screen.");return}var d=oCa(this,c);d||(C7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.hc("Failed to set initial custom receivers: "+g.zg(a))},this)));
C7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);E7(this,new A7(this.l,d),!0)}this.g.Au(b)}else C7("setConnectedScreenStatus: no screen.")};
g.h.CU=function(a){this.ha()?this.hc("Setting connection data on disposed cast v2"):this.g?this.g.Qj(a):this.hc("Setting connection data without a session")};
g.h.FV=function(){this.ha()?this.hc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),E7(this,null)):C7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.lC,this),(0,g.z)(this.GS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.CE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],SBa);g.af(this.g);B7.Z.V.call(this)};
g.h.hc=function(a){g7("Controller",a)};
g.h.mC=function(a,b){this.g==a&&(b||E7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.hS=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),C7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)C7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{C7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:E7(this,
new A7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:E7(this,new z7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:E7(this,new y7(this.l,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.gQ=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return C7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);E7(this,new z7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.GK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.ks,b))};
g.h.lC=function(a){if(!this.ha()){C7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)C7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),E7(this,new y7(this.l,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=o6(this.l.oe(),c.label);
d&&j6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(C7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.af(this.g),this.g=new y7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.mC,this,this.g)),this.g.Qj(null));this.g.zu(a)}}};
g.h.EV=function(){return this.g?this.g.DE():null};
g.h.GS=function(a){this.ha()||(this.hc("Failed to estabilish a session: "+g.zg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&E7(this,null))};
g.h.lS=function(a){C7("Receiver availability updated: "+a);if(!this.ha()){var b=D7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;D7(this)!=b&&this.R("yt-remote-cast2-availability-change",D7(this))}};
g.h.CE=function(){this.ha()||(this.o=pCa(this),C7("Updating custom receivers: "+g.zg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.hc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",D7(this)))};
B7.prototype.setLaunchParams=B7.prototype.CU;B7.prototype.setConnectedScreenStatus=B7.prototype.BU;B7.prototype.stopSession=B7.prototype.FV;B7.prototype.getCastSession=B7.prototype.EV;B7.prototype.requestSession=B7.prototype.requestSession;B7.prototype.init=B7.prototype.init;B7.prototype.dispose=B7.prototype.dispose;var K7=[];g.h=P7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";Q7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Qf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+R7(this):this.H};
g.h.clone=function(){return new P7(V7(this))};g.A(X7,g.IF);g.h=X7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,c8(this,"play")):b8(this,"play"),a8(this,1,T7(Y7(this))),this.R("remotePlayerChange")):Z7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,c8(this,"pause")):b8(this,"pause"),a8(this,2,T7(Y7(this))),this.R("remotePlayerChange")):Z7(this,this.pause)};
g.h.yE=function(a){if(1==this.g){if(this.l){var b=Y7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,c8(this,"seekTo",{newTime:a}))}else b8(this,"seekTo",{newTime:a});a8(this,3,a);this.R("remotePlayerChange")}else Z7(this,g.Fa(this.yE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,c8(this,"stopVideo")):b8(this,"stopVideo");var a=Y7(this);a.index=-1;a.videoId="";Q7(a);$7(this,a);this.R("remotePlayerChange")}else Z7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=Y7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){g7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){g7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);b8(this,"setVolume",e)}c.muted=b;c.volume=a;$7(this,c)}else Z7(this,g.Fa(this.setVolume,a,b))};
g.h.xD=function(a,b){if(1==this.g){var c=Y7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.zg(b.style),g.ec(d,c.l));b8(this,"setSubtitlesTrack",d);$7(this,c)}else Z7(this,g.Fa(this.xD,a,b))};
g.h.uv=function(a,b){if(1==this.g){b8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qb.id});var c=Y7(this);c.audioTrackId=b.Qb.id;$7(this,c)}else Z7(this,g.Fa(this.uv,a,b))};
g.h.xE=function(a,b){if(1==this.g){if(a&&b){var c=Y7(this);U7(c,a,b);$7(this,c)}b8(this,"previous")}else Z7(this,g.Fa(this.xE,a,b))};
g.h.wE=function(a,b){if(1==this.g){if(a&&b){var c=Y7(this);U7(c,a,b);$7(this,c)}b8(this,"next")}else Z7(this,g.Fa(this.wE,a,b))};
g.h.Hx=function(){1==this.g?b8(this,"dismissAutoplay"):Z7(this,this.Hx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}X7.Z.dispose.call(this)};
g.h.V=function(){CCa(this);this.A=null;this.B.clear();W7(this,null);X7.Z.V.call(this)};
g.h.vv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.lC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.dS=function(a,b){this.R(a,b)};
g.h.CP=function(a){if(!a)this.Ql(null),W7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=Y7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)g7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,$7(this,b)}};
g.h.Ql=function(a){g7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),DCa(this),this.R("remotePlayerChange")};
g.h.BP=function(a){a?(DCa(this),this.R("remotePlayerChange")):this.Ql(null)};
g.h.PP=function(){var a=zCa();a&&W7(this,a)};
g.h.hc=function(a){g7("CP",a)};g.A(d8,g.IF);g.h=d8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;S7(this.Za,m);this.A="UNSUPPORTED";e8("Connecting with setPlaylist and params: "+g.zg(l));this.g.connect({method:"setPlaylist",params:g.zg(l)},a,ZAa())}else e8("Connecting without params"),
this.g.connect({},a,ZAa());FCa(this)};
g.h.dispose=function(){this.ha()||(this.R("beforeDispose"),f8(this,3));d8.Z.dispose.call(this)};
g.h.V=function(){g8(this);i8(this);h8(this);g.UD(this.H);this.H=window.NaN;g.UD(this.I);this.I=window.NaN;this.o=null;g.tF(this.P);this.P.length=0;this.g.dispose();d8.Z.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.TI=function(){this.C(2)};
g.h.GP=function(){e8("Channel opened");this.N&&(this.N=!1,h8(this),this.M=g.SD((0,g.z)(function(){e8("Timing out waiting for a screen.");this.C(1)},this),15E3));
cBa(PBa(this.g),this.X)};
g.h.DP=function(){e8("Channel closed");(0,window.isNaN)(this.B)?t6(!0):t6();this.dispose()};
g.h.EP=function(a){t6();(0,window.isNaN)(this.F())?(e8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,e8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),f8(this,2))};
g.h.FP=function(a){a.params?e8("Received: action="+a.action+", params="+g.zg(a.params)):e8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xw(a.params.devices);this.l=(0,g.H)(a,function(a){return new h6(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
ICa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
ICa(this,!1);break;case "remoteConnected":var b=new h6(g.Xw(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new h6(g.Xw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":KCa(this,a);break;case "nowPlaying":MCa(this,a);break;case "onStateChange":LCa(this,a);break;case "onAdStateChange":NCa(this,a);break;case "onVolumeChanged":OCa(this,a);break;case "onSubtitlesTrackChanged":JCa(this,a);break;case "nowAutoplaying":PCa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":QCa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:e8("Unrecognized action: "+a.action)}};
g.h.mU=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&j8(this,"getNowPlaying")}};
d8.prototype.subscribe=d8.prototype.subscribe;d8.prototype.unsubscribeByKey=d8.prototype.Od;d8.prototype.fa=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?b7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
d8.prototype.getProxyState=d8.prototype.fa;d8.prototype.C=function(a){e8("Disconnecting with "+a);g8(this);this.R("beforeDisconnect",a);1==a&&t6();QBa(this.g,a);this.dispose()};
d8.prototype.disconnect=d8.prototype.C;d8.prototype.da=function(){var a=this.Za;this.o&&(a=this.Za.clone(),U7(a,this.o,a.index));return V7(a)};
d8.prototype.getPlayerContextData=d8.prototype.da;
d8.prototype.ma=function(a){var b=new P7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.UD(this.H),this.H=g.SD((0,g.z)(this.mU,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&T7(this.Za)==T7(b)&&g.zg(this.Za.l)==g.zg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
d8.prototype.setPlayerContextData=d8.prototype.ma;d8.prototype.W=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
d8.prototype.getOtherConnectedRemoteId=d8.prototype.W;d8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
d8.prototype.getReconnectTimeout=d8.prototype.F;d8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
d8.prototype.getAutoplayMode=d8.prototype.Y;d8.prototype.ba=function(){return this.D||""};
d8.prototype.getAutoplayVideoId=d8.prototype.ba;d8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.$t(a.g);a.start()}};
d8.prototype.reconnect=d8.prototype.ra;d8.prototype.ia=function(a,b){j8(this,a,b);HCa(this)};
d8.prototype.sendMessage=d8.prototype.ia;g.A(k8,k7);g.h=k8.prototype;g.h.oe=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.add=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Jp=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.cd.$_ubk(this.l[a]);this.l.length=0;this.cd=null;k8.Z.V.call(this)};
g.h.AV=function(){this.R("screenChange")};
g.h.ER=function(){this.R("onlineScreenChange")};
t7.prototype.$_st=t7.prototype.start;t7.prototype.$_gspc=t7.prototype.BV;t7.prototype.$_gsppc=t7.prototype.BE;t7.prototype.$_c=t7.prototype.contains;t7.prototype.$_g=t7.prototype.get;t7.prototype.$_a=t7.prototype.add;t7.prototype.$_un=t7.prototype.Jp;t7.prototype.$_r=t7.prototype.remove;t7.prototype.$_gs=t7.prototype.oe;t7.prototype.$_gos=t7.prototype.AE;t7.prototype.$_s=t7.prototype.subscribe;t7.prototype.$_ubk=t7.prototype.Od;var l8=null,m8=null,B8=null,q8=[];g.p(C8,g.L);g.h=C8.prototype;
g.h.V=function(){g.L.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.jC,this);this.g.unsubscribe("remotePlayerChange",this.Tl,this);this.g.unsubscribe("remoteQueueChange",this.To,this);this.g.unsubscribe("autoplayUpNext",this.GB,this);this.g.unsubscribe("previousNextChange",this.gC,this);this.g.unsubscribe("nowAutoplaying",this.YB,this);this.g.unsubscribe("autoplayDismissed",this.FB,this);this.g=this.F=null};
g.h.HA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(F8(this)){if(!Y7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":Y7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.zj(c[0],c[1]);break;case "control_subtitles_set_track":G8(this,c[0]);break;case "control_set_audio_track":c=c[0],F8(this)&&this.g.uv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();H8(this,0==c?void 0:c);break;case "control_seek":H8(this,c[0]);break;case "control_subtitles_set_track":G8(this,c[0]);break;case "control_set_audio_track":c=c[0],F8(this)&&this.g.uv(this.l.ea(1).videoId,c)}};
g.h.AP=function(a){this.K.NI(a)};
g.h.dV=function(a){this.HA("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.JD=function(){var a=this.l.Ac("captions","track");g.Yb(a)||G8(this,a)};
g.h.WB=function(a){if(F8(this)){this.g.unsubscribe("remotePlayerChange",this.Tl,this);var b=Math.round(a.volume);a=!!a.muted;var c=Y7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Tl,this)}};
g.h.VQ=function(){g.Yb(this.C)||bDa(this,this.C);this.D=!1};
g.h.jC=function(a,b){this.B.stop();2==b&&this.GD()};
g.h.Tl=function(){if(F8(this)){this.A.stop();var a=Y7(this.g);switch(a.g){case 1081:case 1:E8(this,new g.VO(8));this.FD();break;case 1085:case 3:E8(this,new g.VO(9));break;case 1083:case 0:E8(this,new g.VO(2));this.I.stop();D8(this,this.l.ea().lengthSeconds);break;case 1084:E8(this,new g.VO(4));break;case 2:E8(this,new g.VO(4));D8(this,T7(a));break;case -1:E8(this,new g.VO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},E8(this,new g.VO(128,a))}a=Y7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,bDa(this,a));a=Y7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.lE()}else aDa(this)};
g.h.gC=function(){this.l.R("mdxpreviousnextchange")};
g.h.To=function(){F8(this)||aDa(this)};
g.h.ZH=function(){this.g.Hx()};
g.h.GB=function(a){a&&(a=g.pE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.gT,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.gT=function(a,b){var c=new g.VN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.YB=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.FB=function(){this.l.R("mdxautoplaycanceled")};
g.h.FN=function(a,b){-1==Y7(this.g).g?H8(this,a):b&&this.g.yE(a)};
g.h.lE=function(){if(F8(this)){var a=Y7(this.g);this.o.Ba(this.P);a.muted?this.l.mute():this.l.cg();this.l.setVolume(a.volume);this.P=this.o.O(this.l,"onVolumeChange",this.WB)}};
g.h.FD=function(){this.A.stop();if(!this.g.ha()){var a=Y7(this.g);a.kb()&&E8(this,new g.VO(8));D8(this,T7(a));this.A.start()}};
g.h.GD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(I8,g.W);I8.prototype.A=function(a){dDa(this,a.state)};g.p(J8,g.LZ);J8.prototype.I=function(){var a=this.l.Ac("remote","receivers");a&&1<a.length&&!this.l.Ac("remote","quickCast")?(this.F=g.lb(a,this.B,this),g.MZ(this,(0,g.H)(a,this.B)),a=this.l.Ac("remote","currentReceiver"),this.rf(this.B(a)),this.enable(!0)):this.enable(!1)};
J8.prototype.B=function(a){return a.key};
J8.prototype.qf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
J8.prototype.wd=function(a){g.LZ.prototype.wd.call(this,a);this.l.Ld("remote","currentReceiver",this.F[a]);this.A.Rb()};g.p(K8,g.rV);g.h=K8.prototype;g.h.create=function(){VCa(g.mM(g.Y(this.g)));this.C.push(g.UF("yt-remote-before-disconnect",this.wP,this));this.C.push(g.UF("yt-remote-connection-change",this.mS,this));this.C.push(g.UF("yt-remote-receiver-availability-change",this.hC,this));this.C.push(g.UF("yt-remote-auto-connect",this.kS,this));this.C.push(g.UF("yt-remote-receiver-resumed",this.jS,this));this.hC()};
g.h.load=function(){this.g.kt();g.rV.prototype.load.call(this);this.B=new C8(this,this.g,this.l);var a=(a=$Ca())?a.currentTime:0;var b=A8()?new X7(v8(),void 0):null;0==a&&b&&(a=T7(Y7(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));cDa(this,this.D,this.D);g.X_(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.bf(this.B,this.l);this.l=this.B=null;g.rV.prototype.unload.call(this);g.X_(this.g.app,5)};
g.h.V=function(){g.VF(this.C);g.rV.prototype.V.call(this)};
g.h.Il=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.HA.apply(this.B,[a].concat(g.qa(c)))};
g.h.JI=function(){return this.loaded?this.B.suggestion:null};
g.h.Qf=function(){return this.l?Y7(this.l).Qf:!1};
g.h.hasNext=function(){return this.l?Y7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.tN=function(){var a=Y7(this.l),b=this.g.ea();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+R7(a):a.A,isPeggedToLive:1>=(a.C?a.o+R7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+R7(a):a.o,seekableStart:0<a.B?a.B+R7(a):a.B}};
g.h.uN=function(){this.l&&this.l.wE()};
g.h.vN=function(){this.l&&this.l.xE()};
g.h.wP=function(a){1==a&&(this.I=this.l?Y7(this.l):null)};
g.h.mS=function(){var a=A8()?new X7(v8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.af(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.jA(a.videoId,T7(a)));this.g.R("videodatachange","newdata",this.g.ea(),3)};
g.h.hC=function(){this.F=[this.o].concat(XCa());var a=w8()||this.o;L8(this,a);this.g.ua("onMdxReceiversChange")};
g.h.kS=function(){var a=w8();L8(this,a)};
g.h.jS=function(){this.A=w8()};
g.h.sN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?N7():L8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&N7(),!0):!1}};
g.h.wN=function(){b8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qc=function(){return!1};g.fY.remote=K8;})(_yt_player);
